# Generated by Django 6.0.6 on 2026-08-01 07:46

from django.db import migrations, models


def copy_category_to_categories(apps, schema_editor):
    """Copy each product's single FK category into the new M2M categories field."""
    Product = apps.get_model('core', 'Product')
    for product in Product.objects.all():
        if product.category_id:
            product.categories.add(product.category_id)


def copy_categories_to_category(apps, schema_editor):
    """Reverse: pick the first category from M2M and assign to FK (best-effort)."""
    Product = apps.get_model('core', 'Product')
    for product in Product.objects.all():
        first_cat = product.categories.first()
        if first_cat:
            product.category_id = first_cat.id
            product.save(update_fields=['category_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_category_order_and_more'),
    ]

    operations = [
        # Step 1: Add the new M2M field (old FK still exists)
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.category'),
        ),
        # Step 2: Copy data from FK to M2M
        migrations.RunPython(
            copy_category_to_categories,
            reverse_code=copy_categories_to_category,
        ),
        # Step 3: Remove the old FK column
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
