# Generated by Django 6.0.6 on 2026-08-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which product is displayed (lower numbers first)'),
        ),
    ]
